# Copyright Â© 2021 Cask Data, Inc.
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

# This workflow will force refresh a feature/65-bq-conf branch with a set of
# feature branches for a BQ Pushdown POC
name: Make POC

on: [push, workflow_dispatch]
jobs:
  make-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          path: result
          ref: release/6.5
          fetch-depth: 0
      - name: Refresh branch
        run: |
          cd result
          git config --global user.email "vitaliit@google.com"
          git config --global user.name "Vitalii Tymchyshyn (Auto Merge)"
          # Add more feature branches as needed
          for BRANCH in feature/bq_sink_pushdown
          do
            git cherry-pick $(git merge-base origin/develop origin/$BRANCH)..origin/$BRANCH
          done
          git push --force origin HEAD:feature/65-bq-poc
